"""empty message

Revision ID: 401e4e9569f7
Revises: 
Create Date: 2019-01-13 10:14:38.207252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '401e4e9569f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('type', sa.String(length=120), nullable=True),
    sa.Column('summary', sa.String(length=300), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip', sa.Integer(), nullable=True),
    sa.Column('takeaway_fact', sa.String(length=300), nullable=True),
    sa.Column('image_url', sa.String(length=300), nullable=True),
    sa.Column('ix_submitted_by', sa.Integer(), nullable=True),
    sa.Column('ix_approved_by', sa.Integer(), nullable=True),
    sa.Column('submission_datetime', sa.DateTime(), nullable=True),
    sa.Column('approval_datetime', sa.DateTime(), nullable=True),
    sa.Column('square_footage', sa.Float(), nullable=True),
    sa.Column('fuel_type', sa.String(length=30), nullable=True),
    sa.Column('fleet_name', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['ix_approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['ix_submitted_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emmissions_statistic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('gges_reduced', sa.Float(), nullable=True),
    sa.Column('ghgs_reduced', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emmissions_statistic')
    op.drop_table('project')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
