"""empty message

Revision ID: e234297f283d
Revises: ab05fd0804ae
Create Date: 2019-01-30 20:24:15.353692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e234297f283d'
down_revision = 'ab05fd0804ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fuel', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('summary', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_owner',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'owner_id')
    )
    op.create_table('site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('GHG_reduced', sa.Float(), nullable=True),
    sa.Column('GGE_reduced', sa.Float(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('area_of_effect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('fuel_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['fuel_type_id'], ['fuel_type.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coordinate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('long', sa.Float(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_of_effect_id', sa.Integer(), nullable=False),
    sa.Column('end_location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_of_effect_id'], ['area_of_effect.id'], ),
    sa.ForeignKeyConstraint(['end_location_id'], ['address.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('radius',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_of_effect_id', sa.Integer(), nullable=False),
    sa.Column('radius', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['area_of_effect_id'], ['area_of_effect.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    op.add_column('project', sa.Column('duration', sa.Interval(), nullable=True))
    op.add_column('project', sa.Column('project_type', sa.String(length=20), nullable=True))
    op.add_column('project', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('project', sa.Column('summary', sa.String(length=1000), nullable=True))
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'GHG_reduced')
    op.drop_column('project', 'user_id')
    op.drop_column('project', 'year')
    op.drop_column('project', 'GGE_reduced')
    op.drop_column('project', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('address', sa.VARCHAR(length=256), nullable=False))
    op.add_column('project', sa.Column('GGE_reduced', sa.FLOAT(), nullable=True))
    op.add_column('project', sa.Column('year', sa.INTEGER(), nullable=False))
    op.add_column('project', sa.Column('user_id', sa.INTEGER(), nullable=False))
    op.add_column('project', sa.Column('GHG_reduced', sa.FLOAT(), nullable=True))
    op.create_foreign_key(None, 'project', 'user', ['user_id'], ['id'])
    op.drop_column('project', 'summary')
    op.drop_column('project', 'start_date')
    op.drop_column('project', 'project_type')
    op.drop_column('project', 'duration')
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=120), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('radius')
    op.drop_table('line')
    op.drop_table('coordinate')
    op.drop_table('area_of_effect')
    op.drop_table('address')
    op.drop_table('site')
    op.drop_table('project_owner')
    op.drop_table('owner')
    op.drop_table('fuel_type')
    # ### end Alembic commands ###
